version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: travelers-album
      POSTGRES_PASSWORD: traveldev
      POSTGRES_DB: travelers_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: